variable "vmRg" {}
variable "location" {}
variable "hostnames" {}
variable "vmSize" {}
variable "subnet" {}
variable "vnet" {}
variable "networkRg" {}
variable "adminUsername" {}
variable "adminPassword" {}
variable "image" {}
variable "tags" {}
variable "zones" {}
variable "disks" {}
